# resources/provider/__init__.py
from .booking_endpoints import ProviderBookingsResource, BookingStatisticsResource, TripBookingsResource
from .dashboard_endpoints import ProviderDashboardResource
from .route_endpoints import ProviderRoutesResource, ProviderRouteDetailResource
from .route_stops_endpoints import ProviderRouteStopsResource, UpdateRouteStopResource, DeleteRouteStopResource
from .stops_endpoints import CreateStopResource, UpdateStopResource, DeleteStopResource
from .trip_endpoints import ProviderRouteTripsResource, ProviderTripResource, CancelTripResource
from .vehicle_endpoints import ListVehiclesResource, CreateVehicleResource, ProviderVehicleResource