"""add is_active to vehicles

Revision ID: d95e862532bf
Revises: 2e2e66f9b1a2
Create Date: 2026-08-26 16:44:44.831475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95e862532bf'
down_revision = '2e2e66f9b1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence', name='uq_route_stops_route_sequence'),
    sa.UniqueConstraint('route_id', 'stop_id', name='uq_route_stops_route_stop')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_routestop_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('destination_routestop_id', sa.Integer(), nullable=False))
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('bookings_origin_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('bookings_destination_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'route_stops', ['destination_routestop_id'], ['id'])
        batch_op.create_foreign_key(None, 'route_stops', ['origin_routestop_id'], ['id'])
        batch_op.drop_column('origin_id')
        batch_op.drop_column('destination_id')

    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('stops_route_id_fkey'), type_='foreignkey')
        batch_op.drop_column('route_id')

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_routestop_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('destination_routestop_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('trips_origin_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('trips_destination_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'route_stops', ['origin_routestop_id'], ['id'])
        batch_op.create_foreign_key(None, 'route_stops', ['destination_routestop_id'], ['id'])
        batch_op.drop_column('origin_id')
        batch_op.drop_column('destination_id')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('origin_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('trips_destination_id_fkey'), 'stops', ['destination_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('trips_origin_id_fkey'), 'stops', ['origin_id'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('destination_routestop_id')
        batch_op.drop_column('origin_routestop_id')

    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('stops_route_id_fkey'), 'routes', ['route_id'], ['id'])

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('origin_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bookings_destination_id_fkey'), 'stops', ['destination_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('bookings_origin_id_fkey'), 'stops', ['origin_id'], ['id'])
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('destination_routestop_id')
        batch_op.drop_column('origin_routestop_id')

    op.drop_table('route_stops')
    # ### end Alembic commands ###
